# -*- mode: python ; coding: utf-8 -*-
#
# PyInstaller spec file for BridgeIt
#
# Build:
#   pip install pyinstaller
#   pyinstaller bridgeit.spec
#
# Output: dist/BridgeIt/   (folder — zip/wrap in installer for distribution)
#
# onnxruntime and rembg both load C extensions and data files dynamically, so
# we use collect_all() which pulls in everything PyInstaller's hook system finds.
# This makes the bundle larger but avoids "DLL not found" at runtime.

import sys
from pathlib import Path
from PyInstaller.utils.hooks import collect_all, collect_data_files

HERE = Path(SPECPATH)

block_cipher = None

# ── Collect complex packages that use dlopen / dynamic loaders ────────────────
datas, binaries, hiddenimports = [], [], []

for pkg in ('rembg', 'onnxruntime'):
    d, b, h = collect_all(pkg)
    datas     += d
    binaries  += b
    hiddenimports += h

# svgwrite ships data files (templates) that collect_data_files picks up
datas += collect_data_files('svgwrite')

# ── Bundle the app's own assets ───────────────────────────────────────────────
datas += [
    (str(HERE / 'bridgeit' / 'assets'), 'bridgeit/assets'),
]

# ── Extra hidden imports not found by static analysis ────────────────────────
hiddenimports += [
    # PyQt6 extras sometimes missed
    'PyQt6.QtSvg',
    'PyQt6.QtSvgWidgets',
    'PyQt6.QtPrintSupport',
    # Pillow
    'PIL._imaging',
    'PIL.ImageQt',
    'PIL.ImageFilter',
    # shapely internals
    'shapely.algorithms.polylabel',
    'shapely.prepared',
    # stdlib modules that get missed in some environments
    'multiprocessing.resource_tracker',
    'multiprocessing.synchronize',
    'pkg_resources.py2_warn',
]

# ── Analysis ──────────────────────────────────────────────────────────────────
a = Analysis(
    [str(HERE / 'main.py')],
    pathex=[str(HERE)],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',        # not needed — saves ~4 MB
        'matplotlib',     # not needed
        'scipy',          # not needed
        'IPython',        # not needed
        'jupyter',        # not needed
        'notebook',       # not needed
    ],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# ── Executable ────────────────────────────────────────────────────────────────
# exclude_binaries=True → folder mode (COLLECT handles the .so/.dll files)
# This is required for onnxruntime which loads its providers via dlopen() and
# cannot find them when everything is packed into a single file.
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='BridgeIt',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[
        # UPX corrupts some Qt and onnxruntime shared libraries — exclude them
        'libQt6*.so*',
        'libonnxruntime*.so*',
        'Qt6*.dll',
        'onnxruntime*.dll',
    ],
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(HERE / 'bridgeit' / 'assets' / 'icon.ico'),
)

# ── Collect: gather exe + all libs into dist/BridgeIt/ ───────────────────────
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[
        'libQt6*.so*',
        'libonnxruntime*.so*',
        'Qt6*.dll',
        'onnxruntime*.dll',
    ],
    name='BridgeIt',
)

# ── macOS .app bundle (only built when targeting macOS) ───────────────────────
if sys.platform == 'darwin':
    app = BUNDLE(
        coll,
        name='BridgeIt.app',
        # .icns is generated by the CI workflow; fall back to .ico on other systems
        icon=str(HERE / 'bridgeit' / 'assets' / 'icon.icns')
              if (HERE / 'bridgeit' / 'assets' / 'icon.icns').exists()
              else str(HERE / 'bridgeit' / 'assets' / 'icon.ico'),
        bundle_identifier='com.outlandfabworks.bridgeit',
        info_plist={
            'NSHighResolutionCapable': True,
            'NSRequiresAquaSystemAppearance': False,
            'CFBundleShortVersionString': '0.6.0',
            'CFBundleName': 'BridgeIt',
            'CFBundleDisplayName': 'BridgeIt',
        },
    )
